version: "3.8"

x-env:
  &env
  LANG: C.UTF-8

services:
  database:
    environment:
      MONGO_INITDB_ROOT_USERNAME: posthelp
      MONGO_INITDB_ROOT_PASSWORD: whoknows123
      MONGO_INITDB_DATABASE: pfdb
      <<: *env
  backend:
    environment:
      <<: *env

